import Foundation

// MARK: - Format

/// One selectable stream reported by `yt-dlp --dump-single-json`.
struct MediaFormat: Identifiable, Hashable, Sendable {
    var id: String
    var ext: String?
    var width: Int?
    var height: Int?
    var fps: Double?
    var videoCodec: String?
    var audioCodec: String?
    var totalBitrate: Double?
    var audioBitrate: Double?
    var sampleRate: Int?
    var fileSize: Int64?
    var note: String?
    var dynamicRange: String?
    var language: String?

    var isAudioOnly: Bool { isNone(videoCodec) && !isNone(audioCodec) }
    var isVideoOnly: Bool { isNone(audioCodec) && !isNone(videoCodec) }
    var isCombined: Bool { !isNone(audioCodec) && !isNone(videoCodec) }

    private func isNone(_ codec: String?) -> Bool {
        guard let codec, !codec.isEmpty else { return true }
        return codec == "none"
    }

    /// `"1080p60"`, `"audio only"`, or the raw note when nothing better is available.
    var qualityLabel: String {
        if isAudioOnly {
            if let audioBitrate { return "\(Int(audioBitrate.rounded())) kbps" }
            return note ?? "audio only"
        }
        if let height {
            let frameRate = (fps ?? 0) >= 50 ? "\(Int(fps!.rounded()))" : ""
            return "\(height)p\(frameRate)"
        }
        return note ?? "—"
    }

    var codecLabel: String {
        let video = isNone(videoCodec) ? nil : shortCodec(videoCodec)
        let audio = isNone(audioCodec) ? nil : shortCodec(audioCodec)
        return [video, audio].compactMap { $0 }.joined(separator: " + ")
    }

    /// yt-dlp reports full codec strings such as `avc1.640028`; only the family is useful here.
    private func shortCodec(_ codec: String?) -> String? {
        guard let codec else { return nil }
        return String(codec.split(separator: ".").first ?? Substring(codec))
    }

    var sizeLabel: String? { Format.bytes(fileSize) }

    /// Sort key that puts the highest-quality video first, then audio.
    var sortRank: Double {
        if let height { return Double(height) * 1000 + (fps ?? 0) }
        if let audioBitrate { return audioBitrate }
        if let totalBitrate { return totalBitrate }
        return 0
    }
}

// MARK: - Playlist entry

struct PlaylistEntry: Identifiable, Hashable, Sendable {
    var id: String
    var title: String
    var url: String?
    var duration: Double?
    var uploader: String?
    var thumbnailURL: URL?
    var index: Int
}

// MARK: - Media info

/// The normalised result of analysing a URL.
struct MediaInfo: Identifiable, Equatable, Sendable {
    var id: String
    var title: String
    var uploader: String?
    var channel: String?
    var mediaDescription: String?
    var duration: Double?
    var thumbnailURL: URL?
    var webpageURL: URL?
    var originalURL: String
    var extractor: String?
    var width: Int?
    var height: Int?
    var uploadDate: Date?
    var viewCount: Int?
    var likeCount: Int?
    var isLive: Bool
    var liveStatus: String?
    var availability: String?
    var ageLimit: Int?
    var formats: [MediaFormat]
    var subtitleLanguages: [String]
    var automaticCaptionLanguages: [String]
    var chapterCount: Int

    // Playlist
    var isPlaylist: Bool
    var playlistEntries: [PlaylistEntry]
    var playlistCount: Int?

    var displayUploader: String? {
        let name = uploader ?? channel
        guard let name, !name.isEmpty else { return nil }
        return name
    }

    var resolutionLabel: String? {
        if let width, let height { return "\(width) × \(height)" }
        if let height { return "\(height)p" }
        // For playlists there is no single resolution; fall back to the best format.
        if let best = formats.filter({ !$0.isAudioOnly }).max(by: { $0.sortRank < $1.sortRank }),
           let height = best.height {
            return "\(height)p"
        }
        return nil
    }

    /// Highest video height offered by any format, used to disable impossible presets.
    var maximumHeight: Int? {
        formats.compactMap(\.height).max() ?? height
    }

    /// Formats worth showing, best first, with obvious duplicates collapsed.
    var displayFormats: [MediaFormat] {
        var seen = Set<String>()
        return formats
            .sorted { $0.sortRank > $1.sortRank }
            .filter { format in
                let key = "\(format.qualityLabel)|\(format.ext ?? "")|\(format.codecLabel)"
                return seen.insert(key).inserted
            }
    }
}

// MARK: - Decoding

/// Decodes the JSON produced by `yt-dlp --dump-single-json`.
///
/// yt-dlp's JSON is generated by many independent extractors, so field presence and even
/// field *types* vary. Every value is therefore read leniently and a missing field never
/// fails the whole decode.
enum MediaInfoDecoder {

    static func decode(_ data: Data, originalURL: String) throws -> MediaInfo {
        let decoder = JSONDecoder()
        let raw = try decoder.decode(RawInfo.self, from: data)
        return makeMediaInfo(from: raw, originalURL: originalURL)
    }

    private static func makeMediaInfo(from raw: RawInfo, originalURL: String) -> MediaInfo {
        let isPlaylist = raw.type == "playlist" || raw.type == "multi_video" || raw.entries != nil

        let entries: [PlaylistEntry] = (raw.entries ?? []).enumerated().map { index, entry in
            PlaylistEntry(
                id: entry.id ?? "\(index)",
                title: entry.title ?? entry.url ?? "Item \(index + 1)",
                url: entry.webpageURL ?? entry.url,
                duration: entry.duration,
                uploader: entry.uploader ?? entry.channel,
                thumbnailURL: entry.thumbnail.flatMap(URL.init(string:)),
                index: index + 1
            )
        }

        // A playlist has no formats of its own; borrow the first entry's artwork so the
        // preview card still shows something meaningful.
        let thumbnail = raw.thumbnail.flatMap(URL.init(string:)) ?? entries.first?.thumbnailURL

        let totalDuration: Double? = {
            if let duration = raw.duration { return duration }
            guard isPlaylist, !entries.isEmpty else { return nil }
            let durations = entries.compactMap(\.duration)
            return durations.isEmpty ? nil : durations.reduce(0, +)
        }()

        return MediaInfo(
            id: raw.id ?? UUID().uuidString,
            title: raw.title ?? raw.webpageURL ?? originalURL,
            uploader: raw.uploader,
            channel: raw.channel,
            mediaDescription: raw.description,
            duration: totalDuration,
            thumbnailURL: thumbnail,
            webpageURL: raw.webpageURL.flatMap(URL.init(string:)),
            originalURL: originalURL,
            extractor: raw.extractorKey ?? raw.extractor,
            width: raw.width,
            height: raw.height,
            uploadDate: Format.parseUploadDate(raw.uploadDate),
            viewCount: raw.viewCount,
            likeCount: raw.likeCount,
            isLive: raw.isLive ?? (raw.liveStatus == "is_live"),
            liveStatus: raw.liveStatus,
            availability: raw.availability,
            ageLimit: raw.ageLimit,
            formats: (raw.formats ?? []).map(makeFormat),
            subtitleLanguages: (raw.subtitles ?? [:]).keys.sorted(),
            automaticCaptionLanguages: (raw.automaticCaptions ?? [:]).keys.sorted(),
            chapterCount: raw.chapters?.count ?? 0,
            isPlaylist: isPlaylist,
            playlistEntries: entries,
            playlistCount: raw.playlistCount ?? (entries.isEmpty ? nil : entries.count)
        )
    }

    private static func makeFormat(_ raw: RawFormat) -> MediaFormat {
        MediaFormat(
            id: raw.formatID ?? UUID().uuidString,
            ext: raw.ext,
            width: raw.width,
            height: raw.height,
            fps: raw.fps,
            videoCodec: raw.vcodec,
            audioCodec: raw.acodec,
            totalBitrate: raw.tbr,
            audioBitrate: raw.abr,
            sampleRate: raw.asr,
            fileSize: raw.filesize ?? raw.filesizeApprox,
            note: raw.formatNote,
            dynamicRange: raw.dynamicRange,
            language: raw.language
        )
    }

    // MARK: Raw shapes

    private struct RawInfo: Decodable {
        var type: String?
        var id: String?
        var title: String?
        var description: String?
        var uploader: String?
        var channel: String?
        var duration: Double?
        var thumbnail: String?
        var webpageURL: String?
        var extractor: String?
        var extractorKey: String?
        var width: Int?
        var height: Int?
        var uploadDate: String?
        var viewCount: Int?
        var likeCount: Int?
        var isLive: Bool?
        var liveStatus: String?
        var availability: String?
        var ageLimit: Int?
        var playlistCount: Int?
        var formats: [RawFormat]?
        var entries: [RawEntry]?
        var subtitles: [String: RawIgnored]?
        var automaticCaptions: [String: RawIgnored]?
        var chapters: [RawIgnored]?

        enum CodingKeys: String, CodingKey {
            case type = "_type"
            case id, title, description, uploader, channel, duration, thumbnail
            case webpageURL = "webpage_url"
            case extractor
            case extractorKey = "extractor_key"
            case width, height
            case uploadDate = "upload_date"
            case viewCount = "view_count"
            case likeCount = "like_count"
            case isLive = "is_live"
            case liveStatus = "live_status"
            case availability
            case ageLimit = "age_limit"
            case playlistCount = "playlist_count"
            case formats, entries, subtitles, chapters
            case automaticCaptions = "automatic_captions"
        }

        init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            type = container.lenientString(.type)
            id = container.lenientString(.id)
            title = container.lenientString(.title)
            description = container.lenientString(.description)
            uploader = container.lenientString(.uploader)
            channel = container.lenientString(.channel)
            duration = container.lenientDouble(.duration)
            thumbnail = container.lenientString(.thumbnail)
            webpageURL = container.lenientString(.webpageURL)
            extractor = container.lenientString(.extractor)
            extractorKey = container.lenientString(.extractorKey)
            width = container.lenientInt(.width)
            height = container.lenientInt(.height)
            uploadDate = container.lenientString(.uploadDate)
            viewCount = container.lenientInt(.viewCount)
            likeCount = container.lenientInt(.likeCount)
            isLive = container.lenientBool(.isLive)
            liveStatus = container.lenientString(.liveStatus)
            availability = container.lenientString(.availability)
            ageLimit = container.lenientInt(.ageLimit)
            playlistCount = container.lenientInt(.playlistCount)
            formats = try? container.decodeIfPresent([RawFormat].self, forKey: .formats)
            entries = try? container.decodeIfPresent([RawEntry].self, forKey: .entries)
            subtitles = try? container.decodeIfPresent([String: RawIgnored].self, forKey: .subtitles)
            automaticCaptions = try? container.decodeIfPresent([String: RawIgnored].self, forKey: .automaticCaptions)
            chapters = try? container.decodeIfPresent([RawIgnored].self, forKey: .chapters)
        }
    }

    private struct RawFormat: Decodable {
        var formatID: String?
        var ext: String?
        var width: Int?
        var height: Int?
        var fps: Double?
        var vcodec: String?
        var acodec: String?
        var tbr: Double?
        var abr: Double?
        var asr: Int?
        var filesize: Int64?
        var filesizeApprox: Int64?
        var formatNote: String?
        var dynamicRange: String?
        var language: String?

        enum CodingKeys: String, CodingKey {
            case formatID = "format_id"
            case ext, width, height, fps, vcodec, acodec, tbr, abr, asr, filesize, language
            case filesizeApprox = "filesize_approx"
            case formatNote = "format_note"
            case dynamicRange = "dynamic_range"
        }

        init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            formatID = container.lenientString(.formatID)
            ext = container.lenientString(.ext)
            width = container.lenientInt(.width)
            height = container.lenientInt(.height)
            fps = container.lenientDouble(.fps)
            vcodec = container.lenientString(.vcodec)
            acodec = container.lenientString(.acodec)
            tbr = container.lenientDouble(.tbr)
            abr = container.lenientDouble(.abr)
            asr = container.lenientInt(.asr)
            filesize = container.lenientInt64(.filesize)
            filesizeApprox = container.lenientInt64(.filesizeApprox)
            formatNote = container.lenientString(.formatNote)
            dynamicRange = container.lenientString(.dynamicRange)
            language = container.lenientString(.language)
        }
    }

    private struct RawEntry: Decodable {
        var id: String?
        var title: String?
        var url: String?
        var webpageURL: String?
        var duration: Double?
        var uploader: String?
        var channel: String?
        var thumbnail: String?

        enum CodingKeys: String, CodingKey {
            case id, title, url, duration, uploader, channel, thumbnail
            case webpageURL = "webpage_url"
        }

        init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            id = container.lenientString(.id)
            title = container.lenientString(.title)
            url = container.lenientString(.url)
            webpageURL = container.lenientString(.webpageURL)
            duration = container.lenientDouble(.duration)
            uploader = container.lenientString(.uploader)
            channel = container.lenientString(.channel)
            thumbnail = container.lenientString(.thumbnail)
        }
    }

    /// Placeholder for structures whose contents we only count.
    private struct RawIgnored: Decodable {
        init(from decoder: Decoder) throws {}
    }
}

// MARK: - Lenient accessors

private extension KeyedDecodingContainer {

    func lenientString(_ key: Key) -> String? {
        if let value = try? decodeIfPresent(String.self, forKey: key) { return value }
        if let value = try? decodeIfPresent(Int.self, forKey: key) { return String(value) }
        if let value = try? decodeIfPresent(Double.self, forKey: key) { return String(value) }
        return nil
    }

    func lenientInt(_ key: Key) -> Int? {
        if let value = try? decodeIfPresent(Int.self, forKey: key) { return value }
        if let value = try? decodeIfPresent(Double.self, forKey: key), value.isFinite {
            return Int(value)
        }
        if let value = try? decodeIfPresent(String.self, forKey: key) { return Int(value) }
        return nil
    }

    func lenientInt64(_ key: Key) -> Int64? {
        if let value = try? decodeIfPresent(Int64.self, forKey: key) { return value }
        if let value = try? decodeIfPresent(Double.self, forKey: key), value.isFinite {
            return Int64(value)
        }
        if let value = try? decodeIfPresent(String.self, forKey: key) { return Int64(value) }
        return nil
    }

    func lenientDouble(_ key: Key) -> Double? {
        if let value = try? decodeIfPresent(Double.self, forKey: key) { return value }
        if let value = try? decodeIfPresent(Int.self, forKey: key) { return Double(value) }
        if let value = try? decodeIfPresent(String.self, forKey: key) { return Double(value) }
        return nil
    }

    func lenientBool(_ key: Key) -> Bool? {
        if let value = try? decodeIfPresent(Bool.self, forKey: key) { return value }
        if let value = try? decodeIfPresent(Int.self, forKey: key) { return value != 0 }
        return nil
    }
}
